stages:
  - build
  - test
  - sonarqube
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble
test:
  stage: test
  dependencies:
    - build
  script:
    - ./gradlew test

sonarqube:
  stage: sonarqube
  dependencies:
    - test
  script:
    - ./gradlew sonarqube

deploy:
  stage: deploy
  dependencies:
    - test
  before_script:
    - ./gradlew assemble
  script:
    - docker build -t cinelux-app:latest .
    - docker run --name cinelux-app-container --rm -dp 8080:8080 cinelux-app

after_script:
  - echo "End CI"
